pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                //sh 'mvn -B -DskipTests clean package'
                sh 'echo Build'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn verify -Dsonar.host.url=http://sonarqube:9000'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
